export const LexicalTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'editor-placeholder',
  paragraph: 'mb-4 text-[12px] leading-relaxed text-slate-600 font-body',
  quote: 'border-l-4 border-[#5F33CC] bg-[#5F33CC]/5 py-2 px-4 rounded-r-lg my-4 italic text-slate-500',
  heading: {
    h1: 'text-3xl font-headline font-bold text-[#36578D] mb-6 mt-8',
    h2: 'text-2xl font-headline font-bold text-[#36578D] mb-4 mt-6',
    h3: 'text-xl font-headline font-bold text-[#36578D] mb-4 mt-6',
    h4: 'text-lg font-headline font-bold text-[#36578D] mb-2 mt-4',
    h5: 'text-md font-headline font-bold text-[#36578D] mb-2 mt-4',
  },
  list: {
    nested: {
      listitem: 'list-none',
    },
    ol: 'list-decimal pl-8 mb-4 space-y-1',
    ul: 'list-disc pl-8 mb-4 space-y-1',
    listitem: 'text-[12px] text-slate-600',
  },
  image: 'rounded-xl max-w-full h-auto border border-white/20 shadow-lg my-6 mx-auto block',
  link: 'text-[#5F33CC] hover:underline cursor-pointer',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-slate-100 px-1 rounded font-mono text-[11px] text-[#5F33CC]',
  },
  code: 'bg-slate-900 text-slate-50 font-mono text-sm p-4 rounded-xl my-4 overflow-x-auto',
  codeHighlight: {
    atrule: 'text-pink-400',
    attr: 'text-yellow-200',
    boolean: 'text-purple-400',
    builtin: 'text-green-400',
    cdata: 'text-slate-400',
    char: 'text-green-400',
    class: 'text-yellow-200',
    'class-name': 'text-yellow-200',
    comment: 'text-slate-400 italic',
    constant: 'text-purple-400',
    deleted: 'text-red-400',
    doctype: 'text-slate-400',
    entity: 'text-slate-400',
    function: 'text-blue-400',
    important: 'text-orange-400',
    inserted: 'text-green-400',
    keyword: 'text-pink-400',
    namespace: 'text-slate-400',
    number: 'text-purple-400',
    operator: 'text-slate-400',
    prolog: 'text-slate-400',
    property: 'text-yellow-200',
    punctuation: 'text-slate-400',
    regex: 'text-orange-400',
    selector: 'text-green-400',
    string: 'text-green-400',
    symbol: 'text-purple-400',
    tag: 'text-pink-400',
    url: 'text-blue-400',
    variable: 'text-blue-400',
  },
  table: 'editor-table',
  tableRow: 'editor-table-row',
  tableCell: 'editor-table-cell',
  tableCellHeader: 'editor-table-cell-header',
  tableSelection: 'editor-table-selected',
};
